export const countryCodesMapping = {
  Afganistán: 'AF',
  Albania: 'AL',
  Alemania: 'DE',
  Algeria: 'DZ',
  Andorra: 'AD',
  Angola: 'AO',
  Anguilla: 'AI',
  'Antigua y Barbuda': 'AG',
  'Antillas Holandesas': 'AN',
  'Arabia Saudita': 'SA',
  Argentina: 'AR',
  Armenia: 'AM',
  Aruba: 'AW',
  Australia: 'AU',
  Austria: 'AT',
  Azerbaiyán: 'AZ',
  Bahamas: 'BS',
  Bahrein: 'BH',
  Bangladesh: 'BD',
  Barbados: 'BB',
  Bélgica: 'BE',
  Belice: 'BZ',
  Belizé: 'BZ',
  Benín: 'BJ',
  Bermudas: 'BM',
  Bielorrusia: 'BY',
  Bolivia: 'BO',
  'Bosnia y Herzegovina': 'BA',
  Botsuana: 'BW',
  Brasil: 'BR',
  Brunéi: 'BN',
  Bulgaria: 'BG',
  'Burkina Faso': 'BF',
  Burundi: 'BI',
  Bután: 'BT',
  'Cabo Verde': 'CV',
  Camboya: 'KH',
  Camerún: 'CM',
  Canadá: 'CA',
  Chad: 'TD',
  Chile: 'CL',
  China: 'CN',
  Chipre: 'CY',
  Colombia: 'CO',
  Comores: 'KM',
  'Congo [Brazzaville]': 'CG',
  'Congo [Kinshasa]': 'CD',
  'Cook, Islas': 'CK',
  'Corea del Norte': 'KP',
  'Corea del Sur': 'KR',
  'Costa de Marfil': 'CI',
  'Costa Rica': 'CR',
  Croacia: 'HR',
  Cuba: 'CU',
  Dinamarca: 'DK',
  'Djibouti, Yibuti': 'DJ',
  Dominica: 'DM',
  Ecuador: 'EC',
  Egipto: 'EG',
  'El Salvador': 'SV',
  'Emiratos árabes Unidos': 'AE',
  Eritrea: 'ER',
  Eslovaquia: 'SK',
  Eslovenia: 'SI',
  España: 'ES',
  'Estados Unidos': 'US',
  'Estados Unidos de Norteamérica': 'US',
  Estonia: 'EE',
  Etiopía: 'ET',
  'Feroe, Islas': 'FO',
  Filipinas: 'PH',
  Finlandia: 'FI',
  Fiyi: 'FJ',
  Francia: 'FR',
  Gabón: 'GA',
  Gambia: 'GM',
  Georgia: 'GE',
  Ghana: 'GH',
  Gibraltar: 'GI',
  Granada: 'GD',
  Grecia: 'GR',
  Groenlandia: 'GL',
  Guadalupe: 'GP',
  Guatemala: 'GT',
  Guernsey: 'GG',
  Guinea: 'GN',
  'Guinea Ecuatorial': 'GQ',
  'Guinea-Bissau': 'GW',
  Guyana: 'GY',
  Haiti: 'HT',
  Haití: 'HT',
  Holanda: 'NL',
  Honduras: 'HN',
  'Hong Kong': 'HK',
  Hungria: 'HU',
  Hungría: 'HU',
  India: 'IN',
  Indonesia: 'ID',
  Irak: 'IQ',
  Irán: 'IR',
  Irlanda: 'IE',
  'Isla Pitcairn': 'PN',
  Islandia: 'IS',
  'Islas Salomón': 'SB',
  'Islas Turcas y Caicos': 'TC',
  'Islas Virgenes Británicas': 'VG',
  Israel: 'IL',
  Italia: 'IT',
  Jamaica: 'JM',
  Japón: 'JP',
  Jersey: 'JE',
  Jordania: 'JO',
  Kazajstán: 'KZ',
  Kenia: 'KE',
  Kirguistán: 'KG',
  Kiribati: 'KI',
  Kuwait: 'KW',
  Laos: 'LA',
  Lesotho: 'LS',
  Letonia: 'LV',
  Líbano: 'LB',
  Liberia: 'LR',
  Libia: 'LY',
  Liechtenstein: 'LI',
  Lituania: 'LT',
  Luxemburgo: 'LU',
  Macedonia: 'MK',
  Madagascar: 'MG',
  Malasia: 'MY',
  Malawi: 'MW',
  Maldivas: 'MV',
  Malí: 'ML',
  Malta: 'MT',
  'Man, Isla de': 'IM',
  Marruecos: 'MA',
  Martinica: 'MQ',
  Mauricio: 'MU',
  Mauritania: 'MR',
  México: 'MX',
  Moldavia: 'MD',
  Mónaco: 'MC',
  Mongolia: 'MN',
  Mozambique: 'MZ',
  Myanmar: 'MM',
  Namibia: 'NA',
  Nauru: 'NR',
  Nepal: 'NP',
  Nicaragua: 'NI',
  Níger: 'NE',
  Nigeria: 'NG',
  'Norfolk Island': 'NF',
  Noruega: 'NO',
  'Nueva Caledonia': 'NC',
  'Nueva Zelanda': 'NZ',
  Omán: 'OM',
  'Otros Paises': 'XX',
  'Países Bajos, Holanda': 'NL',
  Pakistán: 'PK',
  Panamá: 'PA',
  'Papúa-Nueva Guinea': 'PG',
  Paraguay: 'PY',
  Perú: 'PE',
  'Polinesia Francesa': 'PF',
  Polonia: 'PL',
  Portugal: 'PT',
  'Puerto Rico': 'PR',
  Qatar: 'QA',
  'Reino Unido': 'GB',
  'República Checa': 'CZ',
  'República Dominicana': 'DO',
  'Repulica Dominicana': 'DO', // Typo in "República Dominicana"
  Reunión: 'RE',
  Ruanda: 'RW',
  Rumania: 'RO',
  Rumanía: 'RO', // Typo in "Rumania"
  Rusia: 'RU',
  'Sáhara Occidental': 'EH',
  Samoa: 'WS',
  'San Cristobal y Nevis': 'KN',
  'San Marino': 'SM',
  'San Pedro y Miquelón': 'PM',
  'San Tomé y Príncipe': 'ST',
  'San Vincente y Granadinas': 'VC',
  'Santa Elena': 'SH',
  'Santa Lucía': 'LC',
  Senegal: 'SN',
  'Serbia y Montenegro': 'CS', // Deprecated, use separate codes for Serbia (RS) and Montenegro (ME)
  Seychelles: 'SC',
  'Sierra Leona': 'SL',
  Singapur: 'SG',
  Siria: 'SY',
  Somalia: 'SO',
  'Sri Lanka': 'LK',
  Sudáfrica: 'ZA',
  Sudán: 'SD',
  Suecia: 'SE',
  Suiza: 'CH',
  Surinam: 'SR',
  Swazilandia: 'SZ',
  Tadjikistan: 'TJ',
  Tailandia: 'TH',
  Taiwan: 'TW',
  Tanzania: 'TZ',
  'Timor Oriental': 'TL',
  Togo: 'TG',
  Tokelau: 'TK',
  Tonga: 'TO',
  'Trinidad y Tobago': 'TT',
  Túnez: 'TN',
  Turkmenistan: 'TM',
  Turquía: 'TR',
  Tuvalu: 'TV',
  Ucrania: 'UA',
  Uganda: 'UG',
  Uruguay: 'UY',
  Uzbekistán: 'UZ',
  Vanuatu: 'VU',
  Venezuela: 'VE',
  Vietnam: 'VN',
  'Wallis y Futuna': 'WF',
  Yemen: 'YE',
  Yugoslavia: 'YU', // Deprecated, no longer in use
  Zambia: 'ZM',
  Zimbabwe: 'ZW',
};
