export enum RegisterStepEnum {
  DOCUMENT_VALIDATION = 0,
  FACEPHI = 1,
  EMAIL_REGISTRATION = 2,
  EMAIL_VERIFICATION = 3,
  NAME_VALIDATION = 4,
  PHONE_VALIDATION = 5,
  PASSWORD_VALIDATION = 6,
}

export enum CollaboratorRegisterStepEnum {
  DOCUMENT_VALIDATION = 0,
  EMAIL_REGISTRATION = 1,
  OPEN_IDENTITY_VALIDATION = 2,
  IDENTITY_VALIDATION = 3,
  CREATION_PASSWORD = 4,
}

export enum FacialStateEnum {
  INITIAL_VALIDATION = 0,
  VALIDATION_UNSUCCESS = 1,
  VALIDATION_SUCCESS = 2,
  LIMIT_SHIPMENTS_FACIAL = 3,
  LIMIT_SHIPMENTS = 4,
}
export enum AutocaptureFacialStateEnum {
  FRONT_DOCUMENT = 0,
  BACK_DOCUMENT = 1,
  IDENTITY_VALIDATION = 2,
  LIMIT_SHIPMENTS = 3,
  SUCCESS = 4,
}
