export enum DocumentTagEnum {
  CONTRATO_ADMINISTRACION = 'CONTRATO_ADMINISTRACION',
  REGLAMENTO_FONDOS_MUTUOS = 'REGLAMENTO_FONDOS_MUTUOS',
  ANEXO_REGLAMENTO = 'ANEXO_REGLAMENTO',
  PROSPECTO_SIMPLIFICADO = 'PROSPECTO_SIMPLIFICADO',
  PUBLICITY_FUND = 'PUBLICITY_FUND',
}
