export enum PublicUserEnum {
  EMAIL = 'public@prudentialsaf.com.pe',
  PASSWORD = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDk4ZGJkLTQ4MzMtNDEzYS05YjU0LWFhMGZjYTVlNTk5OSIsIm5hbWUiOiJwdWJsaWMiLCJsYXN0bmFtZSI6InB1YmxpYyIsImVtYWlsIjoicHVibGljQHBydWRlbnRpYWxzYWYuY29tLnBlIiwidXNlcm5hbWUiOiJwdWJsaWMiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfbnVtYmVyIjpudWxsLCJzdGF0dXMiOjEsImlzQWRtaW4iOnRydWUsImlhdCI6MTc0MzgwNTgzNiwiZXhwIjoxNzQzODEzMDM2fQ.kdmWXaoj2QhSXUDihnTM-CgGN4V9F2nKwV6xWLJy6Cs',
}
