export enum NaturalClientFormEnum {
  IDENTIFY_CUSTOMER_FORM = 'IDENTIFY_CUSTOMER_FORM',
  PERSONAL_INFORMATION_FORM = 'PERSONAL_INFORMATION_FORM',
  ACTIVITY_CUSTOMER_FORM = 'ACTIVITY_CUSTOMER_FORM',
  HOME_CUSTOMER_FORM = 'HOME_CUSTOMER_FORM',
  SPOUSE_CUSTOMER_FORM = 'SPOUSE_CUSTOMER_FORM',
  FINAL_BENEFICIARY_FORM = 'FINAL_BENEFICIARY_FORM',
}
